// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: proto/CI.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *BuildID) Reset() {
	*x = BuildID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_CI_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildID) ProtoMessage() {}

func (x *BuildID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_CI_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildID.ProtoReflect.Descriptor instead.
func (*BuildID) Descriptor() ([]byte, []int) {
	return file_proto_CI_proto_rawDescGZIP(), []int{0}
}

func (x *BuildID) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type Build struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	GithubRepoID  int64                  `protobuf:"varint,2,opt,name=GithubRepoID,proto3" json:"GithubRepoID,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=Branch,proto3" json:"Branch,omitempty"`
	IsSuccessfull bool                   `protobuf:"varint,4,opt,name=IsSuccessfull,proto3" json:"IsSuccessfull,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Stdout        string                 `protobuf:"bytes,6,opt,name=Stdout,proto3" json:"Stdout,omitempty"`
}

func (x *Build) Reset() {
	*x = Build{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_CI_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Build) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Build) ProtoMessage() {}

func (x *Build) ProtoReflect() protoreflect.Message {
	mi := &file_proto_CI_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Build.ProtoReflect.Descriptor instead.
func (*Build) Descriptor() ([]byte, []int) {
	return file_proto_CI_proto_rawDescGZIP(), []int{1}
}

func (x *Build) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Build) GetGithubRepoID() int64 {
	if x != nil {
		return x.GithubRepoID
	}
	return 0
}

func (x *Build) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Build) GetIsSuccessfull() bool {
	if x != nil {
		return x.IsSuccessfull
	}
	return false
}

func (x *Build) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Build) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

type BuildList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size   int64    `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
	Builds []*Build `protobuf:"bytes,2,rep,name=Builds,proto3" json:"Builds,omitempty"`
}

func (x *BuildList) Reset() {
	*x = BuildList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_CI_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildList) ProtoMessage() {}

func (x *BuildList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_CI_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildList.ProtoReflect.Descriptor instead.
func (*BuildList) Descriptor() ([]byte, []int) {
	return file_proto_CI_proto_rawDescGZIP(), []int{2}
}

func (x *BuildList) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BuildList) GetBuilds() []*Build {
	if x != nil {
		return x.Builds
	}
	return nil
}

type BuildQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GithubRepoID int64  `protobuf:"varint,1,opt,name=GithubRepoID,proto3" json:"GithubRepoID,omitempty"`
	Branch       string `protobuf:"bytes,2,opt,name=Branch,proto3" json:"Branch,omitempty"`
}

func (x *BuildQuery) Reset() {
	*x = BuildQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_CI_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildQuery) ProtoMessage() {}

func (x *BuildQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_CI_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildQuery.ProtoReflect.Descriptor instead.
func (*BuildQuery) Descriptor() ([]byte, []int) {
	return file_proto_CI_proto_rawDescGZIP(), []int{3}
}

func (x *BuildQuery) GetGithubRepoID() int64 {
	if x != nil {
		return x.GithubRepoID
	}
	return 0
}

func (x *BuildQuery) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type ArtifactID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ArtifactID) Reset() {
	*x = ArtifactID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_CI_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactID) ProtoMessage() {}

func (x *ArtifactID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_CI_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactID.ProtoReflect.Descriptor instead.
func (*ArtifactID) Descriptor() ([]byte, []int) {
	return file_proto_CI_proto_rawDescGZIP(), []int{4}
}

func (x *ArtifactID) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type Artifact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	BuildID int64  `protobuf:"varint,2,opt,name=BuildID,proto3" json:"BuildID,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_CI_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_CI_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_proto_CI_proto_rawDescGZIP(), []int{5}
}

func (x *Artifact) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Artifact) GetBuildID() int64 {
	if x != nil {
		return x.BuildID
	}
	return 0
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ArtifactList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size      int64       `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
	Artifacts []*Artifact `protobuf:"bytes,2,rep,name=Artifacts,proto3" json:"Artifacts,omitempty"`
}

func (x *ArtifactList) Reset() {
	*x = ArtifactList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_CI_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactList) ProtoMessage() {}

func (x *ArtifactList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_CI_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactList.ProtoReflect.Descriptor instead.
func (*ArtifactList) Descriptor() ([]byte, []int) {
	return file_proto_CI_proto_rawDescGZIP(), []int{6}
}

func (x *ArtifactList) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ArtifactList) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type ArtifactQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GithubRepoID int64  `protobuf:"varint,1,opt,name=GithubRepoID,proto3" json:"GithubRepoID,omitempty"`
	Branch       string `protobuf:"bytes,2,opt,name=Branch,proto3" json:"Branch,omitempty"`
}

func (x *ArtifactQuery) Reset() {
	*x = ArtifactQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_CI_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactQuery) ProtoMessage() {}

func (x *ArtifactQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_CI_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactQuery.ProtoReflect.Descriptor instead.
func (*ArtifactQuery) Descriptor() ([]byte, []int) {
	return file_proto_CI_proto_rawDescGZIP(), []int{7}
}

func (x *ArtifactQuery) GetGithubRepoID() int64 {
	if x != nil {
		return x.GithubRepoID
	}
	return 0
}

func (x *ArtifactQuery) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

var File_proto_CI_proto protoreflect.FileDescriptor

var file_proto_CI_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x43, 0x49, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x6b, 0x69, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x19, 0x0a, 0x07,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0xcb, 0x01, 0x0a, 0x05, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x22, 0x0a, 0x0c, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x52, 0x65, 0x70, 0x6f, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x52,
	0x65, 0x70, 0x6f, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x24, 0x0a,
	0x0d, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66,
	0x75, 0x6c, 0x6c, 0x12, 0x38, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53,
	0x74, 0x64, 0x6f, 0x75, 0x74, 0x22, 0x49, 0x0a, 0x09, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x69, 0x74, 0x61, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x06, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x73,
	0x22, 0x48, 0x0a, 0x0a, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x22,
	0x0a, 0x0c, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x52, 0x65, 0x70, 0x6f, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x52, 0x65, 0x70, 0x6f,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x22, 0x1c, 0x0a, 0x0a, 0x41, 0x72,
	0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0x48, 0x0a, 0x08, 0x41, 0x72, 0x74, 0x69,
	0x66, 0x61, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x55, 0x0a, 0x0c, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61,
	0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6b, 0x69, 0x74, 0x61,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x09,
	0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x22, 0x4b, 0x0a, 0x0d, 0x41, 0x72, 0x74,
	0x69, 0x66, 0x61, 0x63, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x47, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x52, 0x65, 0x70, 0x6f, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x52, 0x65, 0x70, 0x6f, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x32, 0x85, 0x02, 0x0a, 0x02, 0x43, 0x49, 0x12, 0x36, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x42, 0x79, 0x49, 0x44, 0x12, 0x12, 0x2e,
	0x6b, 0x69, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x49,
	0x44, 0x1a, 0x10, 0x2e, 0x6b, 0x69, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x73, 0x12, 0x15, 0x2e, 0x6b, 0x69, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x14, 0x2e, 0x6b,
	0x69, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x66,
	0x61, 0x63, 0x74, 0x65, 0x42, 0x79, 0x49, 0x44, 0x12, 0x15, 0x2e, 0x6b, 0x69, 0x74, 0x61, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x49, 0x44, 0x1a,
	0x13, 0x2e, 0x6b, 0x69, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x72, 0x74, 0x69,
	0x66, 0x61, 0x63, 0x74, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x12, 0x18, 0x2e, 0x6b, 0x69, 0x74, 0x61,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x1a, 0x17, 0x2e, 0x6b, 0x69, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x42, 0x04,
	0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_CI_proto_rawDescOnce sync.Once
	file_proto_CI_proto_rawDescData = file_proto_CI_proto_rawDesc
)

func file_proto_CI_proto_rawDescGZIP() []byte {
	file_proto_CI_proto_rawDescOnce.Do(func() {
		file_proto_CI_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_CI_proto_rawDescData)
	})
	return file_proto_CI_proto_rawDescData
}

var file_proto_CI_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_CI_proto_goTypes = []interface{}{
	(*BuildID)(nil),               // 0: kitaproto.BuildID
	(*Build)(nil),                 // 1: kitaproto.Build
	(*BuildList)(nil),             // 2: kitaproto.BuildList
	(*BuildQuery)(nil),            // 3: kitaproto.BuildQuery
	(*ArtifactID)(nil),            // 4: kitaproto.ArtifactID
	(*Artifact)(nil),              // 5: kitaproto.Artifact
	(*ArtifactList)(nil),          // 6: kitaproto.ArtifactList
	(*ArtifactQuery)(nil),         // 7: kitaproto.ArtifactQuery
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_proto_CI_proto_depIdxs = []int32{
	8, // 0: kitaproto.Build.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 1: kitaproto.BuildList.Builds:type_name -> kitaproto.Build
	5, // 2: kitaproto.ArtifactList.Artifacts:type_name -> kitaproto.Artifact
	0, // 3: kitaproto.CI.GetBuildByID:input_type -> kitaproto.BuildID
	3, // 4: kitaproto.CI.GetAllBuilds:input_type -> kitaproto.BuildQuery
	4, // 5: kitaproto.CI.GetArtifacteByID:input_type -> kitaproto.ArtifactID
	7, // 6: kitaproto.CI.GetAllArtifacts:input_type -> kitaproto.ArtifactQuery
	1, // 7: kitaproto.CI.GetBuildByID:output_type -> kitaproto.Build
	2, // 8: kitaproto.CI.GetAllBuilds:output_type -> kitaproto.BuildList
	5, // 9: kitaproto.CI.GetArtifacteByID:output_type -> kitaproto.Artifact
	6, // 10: kitaproto.CI.GetAllArtifacts:output_type -> kitaproto.ArtifactList
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_CI_proto_init() }
func file_proto_CI_proto_init() {
	if File_proto_CI_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_CI_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_CI_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Build); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_CI_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_CI_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_CI_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtifactID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_CI_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Artifact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_CI_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtifactList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_CI_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtifactQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_CI_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_CI_proto_goTypes,
		DependencyIndexes: file_proto_CI_proto_depIdxs,
		MessageInfos:      file_proto_CI_proto_msgTypes,
	}.Build()
	File_proto_CI_proto = out.File
	file_proto_CI_proto_rawDesc = nil
	file_proto_CI_proto_goTypes = nil
	file_proto_CI_proto_depIdxs = nil
}
