// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: proto/CI.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CIClient is the client API for CI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CIClient interface {
	GetBuildByID(ctx context.Context, in *BuildID, opts ...grpc.CallOption) (*Build, error)
	GetAllBuilds(ctx context.Context, in *BuildQuery, opts ...grpc.CallOption) (*BuildList, error)
	GetArtifacteByID(ctx context.Context, in *ArtifactID, opts ...grpc.CallOption) (*Artifact, error)
	GetAllArtifacts(ctx context.Context, in *ArtifactQuery, opts ...grpc.CallOption) (*ArtifactList, error)
}

type cIClient struct {
	cc grpc.ClientConnInterface
}

func NewCIClient(cc grpc.ClientConnInterface) CIClient {
	return &cIClient{cc}
}

func (c *cIClient) GetBuildByID(ctx context.Context, in *BuildID, opts ...grpc.CallOption) (*Build, error) {
	out := new(Build)
	err := c.cc.Invoke(ctx, "/kitaproto.CI/GetBuildByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cIClient) GetAllBuilds(ctx context.Context, in *BuildQuery, opts ...grpc.CallOption) (*BuildList, error) {
	out := new(BuildList)
	err := c.cc.Invoke(ctx, "/kitaproto.CI/GetAllBuilds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cIClient) GetArtifacteByID(ctx context.Context, in *ArtifactID, opts ...grpc.CallOption) (*Artifact, error) {
	out := new(Artifact)
	err := c.cc.Invoke(ctx, "/kitaproto.CI/GetArtifacteByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cIClient) GetAllArtifacts(ctx context.Context, in *ArtifactQuery, opts ...grpc.CallOption) (*ArtifactList, error) {
	out := new(ArtifactList)
	err := c.cc.Invoke(ctx, "/kitaproto.CI/GetAllArtifacts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CIServer is the server API for CI service.
// All implementations must embed UnimplementedCIServer
// for forward compatibility
type CIServer interface {
	GetBuildByID(context.Context, *BuildID) (*Build, error)
	GetAllBuilds(context.Context, *BuildQuery) (*BuildList, error)
	GetArtifacteByID(context.Context, *ArtifactID) (*Artifact, error)
	GetAllArtifacts(context.Context, *ArtifactQuery) (*ArtifactList, error)
	mustEmbedUnimplementedCIServer()
}

// UnimplementedCIServer must be embedded to have forward compatible implementations.
type UnimplementedCIServer struct {
}

func (UnimplementedCIServer) GetBuildByID(context.Context, *BuildID) (*Build, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBuildByID not implemented")
}
func (UnimplementedCIServer) GetAllBuilds(context.Context, *BuildQuery) (*BuildList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllBuilds not implemented")
}
func (UnimplementedCIServer) GetArtifacteByID(context.Context, *ArtifactID) (*Artifact, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArtifacteByID not implemented")
}
func (UnimplementedCIServer) GetAllArtifacts(context.Context, *ArtifactQuery) (*ArtifactList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllArtifacts not implemented")
}
func (UnimplementedCIServer) mustEmbedUnimplementedCIServer() {}

// UnsafeCIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CIServer will
// result in compilation errors.
type UnsafeCIServer interface {
	mustEmbedUnimplementedCIServer()
}

func RegisterCIServer(s grpc.ServiceRegistrar, srv CIServer) {
	s.RegisterService(&CI_ServiceDesc, srv)
}

func _CI_GetBuildByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CIServer).GetBuildByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kitaproto.CI/GetBuildByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CIServer).GetBuildByID(ctx, req.(*BuildID))
	}
	return interceptor(ctx, in, info, handler)
}

func _CI_GetAllBuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CIServer).GetAllBuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kitaproto.CI/GetAllBuilds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CIServer).GetAllBuilds(ctx, req.(*BuildQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _CI_GetArtifacteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtifactID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CIServer).GetArtifacteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kitaproto.CI/GetArtifacteByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CIServer).GetArtifacteByID(ctx, req.(*ArtifactID))
	}
	return interceptor(ctx, in, info, handler)
}

func _CI_GetAllArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtifactQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CIServer).GetAllArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kitaproto.CI/GetAllArtifacts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CIServer).GetAllArtifacts(ctx, req.(*ArtifactQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// CI_ServiceDesc is the grpc.ServiceDesc for CI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kitaproto.CI",
	HandlerType: (*CIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBuildByID",
			Handler:    _CI_GetBuildByID_Handler,
		},
		{
			MethodName: "GetAllBuilds",
			Handler:    _CI_GetAllBuilds_Handler,
		},
		{
			MethodName: "GetArtifacteByID",
			Handler:    _CI_GetArtifacteByID_Handler,
		},
		{
			MethodName: "GetAllArtifacts",
			Handler:    _CI_GetAllArtifacts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/CI.proto",
}
