// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: proto/CIJob.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CIJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoURL     string `protobuf:"bytes,1,opt,name=RepoURL,proto3" json:"RepoURL,omitempty"`
	RepoID      int64  `protobuf:"varint,2,opt,name=RepoID,proto3" json:"RepoID,omitempty"`
	Branch      string `protobuf:"bytes,3,opt,name=Branch,proto3" json:"Branch,omitempty"`
	User        string `protobuf:"bytes,4,opt,name=User,proto3" json:"User,omitempty"`
	HeadSHA     string `protobuf:"bytes,5,opt,name=HeadSHA,proto3" json:"HeadSHA,omitempty"`
	AccessToken string `protobuf:"bytes,6,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
}

func (x *CIJob) Reset() {
	*x = CIJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_CIJob_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CIJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIJob) ProtoMessage() {}

func (x *CIJob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_CIJob_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIJob.ProtoReflect.Descriptor instead.
func (*CIJob) Descriptor() ([]byte, []int) {
	return file_proto_CIJob_proto_rawDescGZIP(), []int{0}
}

func (x *CIJob) GetRepoURL() string {
	if x != nil {
		return x.RepoURL
	}
	return ""
}

func (x *CIJob) GetRepoID() int64 {
	if x != nil {
		return x.RepoID
	}
	return 0
}

func (x *CIJob) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *CIJob) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CIJob) GetHeadSHA() string {
	if x != nil {
		return x.HeadSHA
	}
	return ""
}

func (x *CIJob) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

var File_proto_CIJob_proto protoreflect.FileDescriptor

var file_proto_CIJob_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x43, 0x49, 0x4a, 0x6f, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6b, 0x69, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1,
	0x01, 0x0a, 0x05, 0x43, 0x49, 0x4a, 0x6f, 0x62, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x70, 0x6f,
	0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x70, 0x6f, 0x55,
	0x52, 0x4c, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x70, 0x6f, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x52, 0x65, 0x70, 0x6f, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x65, 0x61, 0x64, 0x53, 0x48,
	0x41, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x48, 0x65, 0x61, 0x64, 0x53, 0x48, 0x41,
	0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_CIJob_proto_rawDescOnce sync.Once
	file_proto_CIJob_proto_rawDescData = file_proto_CIJob_proto_rawDesc
)

func file_proto_CIJob_proto_rawDescGZIP() []byte {
	file_proto_CIJob_proto_rawDescOnce.Do(func() {
		file_proto_CIJob_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_CIJob_proto_rawDescData)
	})
	return file_proto_CIJob_proto_rawDescData
}

var file_proto_CIJob_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_CIJob_proto_goTypes = []interface{}{
	(*CIJob)(nil), // 0: kitaproto.CIJob
}
var file_proto_CIJob_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_CIJob_proto_init() }
func file_proto_CIJob_proto_init() {
	if File_proto_CIJob_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_CIJob_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CIJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_CIJob_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_CIJob_proto_goTypes,
		DependencyIndexes: file_proto_CIJob_proto_depIdxs,
		MessageInfos:      file_proto_CIJob_proto_msgTypes,
	}.Build()
	File_proto_CIJob_proto = out.File
	file_proto_CIJob_proto_rawDesc = nil
	file_proto_CIJob_proto_goTypes = nil
	file_proto_CIJob_proto_depIdxs = nil
}
